# Generated by Django 2.1.5 on 2019-04-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='USER_LOGIN',
            fields=[
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('user_name', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=35)),
                ('pass_word', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proj1.USER_LOGIN'),
        ),
    ]
