# Generated by Django 2.1.5 on 2019-04-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_college_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('genders', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('students', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.AddField(
            model_name='info',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.College'),
        ),
    ]
