# Generated by Django 2.1.5 on 2019-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20190421_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='estb',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='pic1',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='pic2',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='pic3',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='pic4',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='pic5',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
