# Generated by Django 2.1.5 on 2019-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_auto_20190421_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='facility1',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='facility2',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='facility3',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='facility4',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='facility5',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
