# Generated by Django 2.1.5 on 2019-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_auto_20190425_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='contact1',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='contact2',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='contact3',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course1',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course2',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course3',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course4',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course5',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course6',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='course7',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
